name: embarqueellus
description: "Sistema de Embarque da Equipe Ellus"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0

  # Câmera e Imagens
  image_picker: ^1.1.1
  camera: ^0.10.5+9
  image: ^4.0.17



  # HTTP e APIs
  http: ^1.1.0

  # Códigos de Barras
  google_mlkit_barcode_scanning: ^0.14.1

  # Banco de Dados e Armazenamento
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  shared_preferences: ^2.5.3

  # Reconhecimento Facial
  google_mlkit_face_detection: ^0.13.1



  # Conectividade
  connectivity_plus: ^6.0.3

  # UI
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/arcface.tflite

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/app_icon.png
