// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============================================================================
  // CONFIGURAÇÃO ANDROID - ✅ CONFIGURADO
  // ============================================================================
  // Configurações obtidas do google-services.json
  // Projeto Firebase: embarqueellus
  // Package Name: br.com.embarqueellus
  // ============================================================================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFA6Xq4Mt-FGrc_vI1t9cdW1-nTDLNWH0',
    appId: '1:720926401522:android:84425bf393bf3412fb416b',
    messagingSenderId: '720926401522',
    projectId: 'embarqueellus',
    storageBucket: 'embarqueellus.firebasestorage.app',
  );

  // ============================================================================
  // CONFIGURAÇÃO iOS - ✅ CONFIGURADO
  // ============================================================================
  // Configurações obtidas do GoogleService-Info.plist
  // Projeto Firebase: embarqueellus
  // ============================================================================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCioVECOLEOrn5ZeRo1L2Mu5TBqYcSUxhs',
    appId: '1:720926401522:ios:d8fd0975333ff612fb416b',
    messagingSenderId: '720926401522',
    projectId: 'embarqueellus',
    storageBucket: 'embarqueellus.firebasestorage.app',
    iosBundleId: 'com.example.embarqueellus',
  );
}
