// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============================================================================
  // ⚠️ CONFIGURAÇÃO NECESSÁRIA - ANDROID
  // ============================================================================
  // Para obter essas informações:
  // 1. Acesse: https://console.firebase.google.com/
  // 2. Selecione seu projeto
  // 3. Vá em Configurações do Projeto (ícone de engrenagem) > Geral
  // 4. Role até "Seus apps" e selecione o app Android
  // 5. Copie os valores abaixo do painel de configuração
  // ============================================================================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE',  // Ex: 'AIzaSyC...'
    appId: 'YOUR_ANDROID_APP_ID_HERE',     // Ex: '1:123456789:android:abcdef...'
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',  // Ex: '123456789'
    projectId: 'YOUR_PROJECT_ID_HERE',     // Ex: 'embarque-ellus'
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE',  // Ex: 'embarque-ellus.appspot.com'
  );

  // ============================================================================
  // ⚠️ CONFIGURAÇÃO NECESSÁRIA - iOS
  // ============================================================================
  // Para obter essas informações:
  // 1. Acesse: https://console.firebase.google.com/
  // 2. Selecione seu projeto
  // 3. Vá em Configurações do Projeto (ícone de engrenagem) > Geral
  // 4. Role até "Seus apps" e selecione o app iOS (ou adicione um novo)
  // 5. Copie os valores abaixo do painel de configuração
  // ============================================================================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',      // Ex: 'AIzaSyD...'
    appId: 'YOUR_IOS_APP_ID_HERE',         // Ex: '1:123456789:ios:abcdef...'
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',  // Ex: '123456789'
    projectId: 'YOUR_PROJECT_ID_HERE',     // Ex: 'embarque-ellus'
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE',  // Ex: 'embarque-ellus.appspot.com'
    iosBundleId: 'br.com.embarqueellus',   // Bundle ID do app (provavelmente correto)
  );
}
